import { AuthProvider } from "@/contexts/AuthContext";
import "./globals.css";
import { Inter } from "next/font/google";
import { Navbar } from "@/components/Navbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "useContext sample app",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="ja">
      <body className={inter.className}>
        <AuthProvider>
        <Navbar/>
          {children}
        </AuthProvider>
      </body>
    </html>
  );
}
